apiVersion: batch/v1
kind: CronJob
metadata:
  name: ds-job
spec:
  schedule: 0 5 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ds-job
            image: ds-job
            imagePullPolicy: Never
          restartPolicy: Never
